### ISSUE TITLE
Update setup

### ISSUE THREAD

**Issue by Camilo-HG** [fenfisdi/cdslib_agents#5]
- [x] Update setup including scikit-learn as a dependency
- [x] Can we add more contributors to the setup file?
- [x] Can we add levels of coding-responsibility in the setup file?

**Comment by Luispapiernik** [comment]
Si se pueden agregar múltiples contribuidores en el archivo setup. Con niveles de responsabilidad se hace referencia a quien hace el diseño de la librería, quien hace los test unitarios, quien se encarga de mantener la rama principal limpia ...?
